required = ["github.com/labstack/echo"]

[[constraint]]
    name = "github.com/labstack/echo"
    version = "3.3.8"

[[constraint]]
    name = "upper.io/db.v3"
    version = "3.3.0"

[[constraint]]
    name = "github.com/lib/pq"
    version = "1.0.0" 

[[constraint]]
    name = "github.com/casbin/casbin"
    version = "1.7.0"

[[constraint]]
    name = "github.com/spf13/viper"
    version = "1.3.1"

[[constraint]]
    name = "github.com/stretchr/testify"
    version = "1.2.2"

[[constraint]]
    name = "github.com/golang/protobuf"
    version = "1.2.0"


